In [1]:
#numpy is a pckage or library for scientific computing in python
#most imp obj of np library is numpy.array
#use for mathamtical,stastical,linear algebra opreation
#difff btn python list and np.arrray 
#list-stores refrence of value in memory 
#np.array-store values directly into memory 

creating np array

In [6]:
import numpy as np#importing libraryy
#to create 1d array
a=np.array([1,2,3])
a

array([1, 2, 3])

In [7]:
#crating 2d array
b=np.array([[1,2,3],[3,5,6]])
b

array([[1, 2, 3],
       [3, 5, 6]])

In [8]:
#3d array
#crating 3d array
c=np.array([
    [[1,2]],
    [[3,4]]
])
c

array([[[1, 2]],

       [[3, 4]]])

np.arange()


In [9]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [10]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

reshape function is used to give arrray a reshaping size(coloume and row wise)

In [11]:
np.arange(1,11).reshape(2,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [12]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [13]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

random function is used to genrate arry randomly
syntax-np.random.random((num of rows,num of col))

In [14]:
np.random.random((3,4))

array([[0.9622566 , 0.97524755, 0.15675452, 0.39135848],
       [0.80960382, 0.96514123, 0.5020691 , 0.20329059],
       [0.37152943, 0.73604748, 0.15327002, 0.25828137]])

In [15]:
#linspace function genrate array of number which are evenly spread 
#syntax-np.linspace(range,num of item)
np.linspace(1,10,5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [16]:
#np.identity used to genrte identiy matrix 
#identity matrix have all digonal element=1 and remaining=0
np.identity((4))

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

numpy attribute

In [17]:
a1=np.arange(10)
a

array([1, 2, 3])

In [18]:
a2=np.arange(12,dtype=float).reshape(3,4)
a2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [19]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [20]:
#to check iension of  atrix whether it 1d,2d,3d........nd
#arrayname.ndim


In [21]:
a1.ndim

1

In [22]:
a2.ndim

2

In [23]:
a3.ndim

3

In [24]:
#shape
#shape is used to return number of rows and col array consist
#arrname.shape

In [25]:
a1.shape

(10,)

In [26]:
a2.shape

(3, 4)

In [27]:
a3.shape

(2, 2, 2)

In [28]:
#size returns the size array occopes in memory
#array_name.size

In [29]:
a1.size

10

In [30]:
a2.size

12

In [31]:
a3.size

8

In [32]:
a1.dtype

dtype('int64')

In [33]:
a2.dtype

dtype('float64')

In [34]:
a3.dtype

dtype('int64')

In [35]:
a3=np.arange(8).reshape(2,2,2)
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [37]:
a3.astype(float)

array([[[0., 1.],
        [2., 3.]],

       [[4., 5.],
        [6., 7.]]])

In [43]:
a2.astype(np.int8)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]], dtype=int8)

In [44]:
#array operation 
#scalar operation(+,-,*,/,**)(operation perform by single element array)
#elational operation(=,<=,>+,<,>,!=,==)
#ector operation(use to perform mathamtical operation on two arrays )

In [45]:
a1=np.arange(12).reshape(3,4)
a2=np.arange(12,24).reshape(3,4)

In [46]:
a1*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22]])

In [47]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [52]:
a1[(a1>5)&(a1%3==0)]

array([6, 9])

In [53]:
a3=np.arange(24,36).reshape(3,4)

In [54]:
a3

array([[24, 25, 26, 27],
       [28, 29, 30, 31],
       [32, 33, 34, 35]])

In [55]:
a2+a3

array([[36, 38, 40, 42],
       [44, 46, 48, 50],
       [52, 54, 56, 58]])

min/max/sum/product

In [56]:
a1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [62]:
a=[np.max(a1)]

In [63]:
a

[np.int64(11)]

In [64]:
np.min(a1)

np.int64(0)

In [65]:
np.sum(a1)

np.int64(66)

In [68]:
np.prod(a2)

np.int64(647647525324800)

statistical oprn

In [69]:
np.mean(a1)

np.float64(5.5)

In [70]:
np.mean(a1,axis=0)

array([4., 5., 6., 7.])

In [71]:
np.mean(a1,axis=1)

array([1.5, 5.5, 9.5])

In [72]:
np.std(a1)#return std dev of aray

np.float64(3.452052529534663)

In [73]:
np.var(a1)

np.float64(11.916666666666666)

In [76]:
a1.ndim

2

In [81]:
a2=np.arange(60,72).reshape(4,3)

In [80]:
a2

array([[60, 61, 62],
       [63, 64, 65],
       [66, 67, 68],
       [69, 70, 71]])

In [84]:
np.dot(a1,a2)#dot function is used to convert rows into coloun and column into roes

array([[ 402,  408,  414],
       [1434, 1456, 1478],
       [2466, 2504, 2542]])

In [85]:
np.log(a1)#calculate log of each elemement

C:\Users\visha\AppData\Local\Temp\ipykernel_30288\303136331.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(a1)#calculate log of each elemement


array([[      -inf, 0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947, 1.94591015],
       [2.07944154, 2.19722458, 2.30258509, 2.39789527]])

In [86]:
np.exp(a1)#calcualte exponent of each element in aray

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03],
       [2.98095799e+03, 8.10308393e+03, 2.20264658e+04, 5.98741417e+04]])

round/floor/ceil

In [88]:
np.round([13.24,45.13,47.89,56.99])#converts value to the nearest value

array([13., 45., 48., 57.])

np.floor([6.9,2.5,32.1,78.65])

In [90]:
np.ceil([12.3,12,45.36,87.87])

array([13., 12., 46., 88.])

Indexing and SLICING

In [92]:
a1=np.arange(10)

In [101]:
a2=np.arange(12).reshape(3,4)

In [102]:
a3=np.arange(8).reshape(2,2,2)

In [103]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [104]:
a1[-1]

np.int64(9)

In [105]:
a1[0]

np.int64(0)

In [106]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [108]:
#fetch the  6 from thne sarray
a2[1,2]

np.int64(6)

In [109]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [110]:
#fetch 6 from 3d array
a3[1,1,0]

np.int64(6)

slicing

In [111]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [112]:
a1[2:5]

array([2, 3, 4])

In [113]:
#2d
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [114]:
a2[0,:]

array([0, 1, 2, 3])

In [115]:
a2[::2,::2]

array([[ 0,  2],
       [ 8, 10]])

In [116]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [118]:
a3[1,0:,1]

array([5, 7])

In [119]:
# to iterate indivisual character from more than 1d array
#we use-np.nditer(array_name)


In [120]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [123]:
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7


In [124]:
#transpose
#row<----->colume
#colume<------>rows

In [125]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [126]:
np.transpose(a2)

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [127]:
a2.T

array([[ 0,  4,  8],
       [ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11]])

In [128]:
#ravel()
#ravel functionn is used to convert any diemension of array into 1d array
#2d----->1d
#3d------>1d
#nd_______>1d

In [129]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [130]:
a2.ravel()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [131]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [132]:
a3.ravel()

array([0, 1, 2, 3, 4, 5, 6, 7])

Stacking


In [133]:
#stacking is ude to attach(milllan)more than 1 array(horizontally or vertcally)
#has two types
#hstack,vstack

In [134]:
a4=np.arange(12).reshape(3,4)
a5=np.arange(12,24).reshape(3,4)

In [136]:
a4


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [137]:
a5

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [138]:
np.hstack((a4,a5))

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [139]:
np.vstack((a4,a5))

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [140]:
#split is complitlly opposite of stack it dtach array into subpart


In [141]:
a4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [144]:
np.vsplit(a4,3)

[array([[0, 1, 2, 3]]), array([[4, 5, 6, 7]]), array([[ 8,  9, 10, 11]])]

In [145]:
np.hsplit(a4,2)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]])]

In [146]:
#time of exicuting between pythonlist and np.arrray

In [153]:
#list
a=[i for i in range(10000000)]
b=[i for i in range(10000000)]
c=[]
import time 
start=time.time()
for i in range(len(a)):
    c.append(a[i]+b[i])
print(time.time()-start)

2.8045122623443604


In [154]:
#np.array
import numpy as np
a=np.arange(10000000)
b=np.arange(10000000)
start=time.time()
c=a+b
print(time.time()-start)


0.05136919021606445


In [155]:

2.8045122623443604/0.05136919021606445


54.59522041418745

In [156]:
#memory diff betn arraylist vs np.array

In [157]:
#list
a=[i for i in range(10000000)]
import sys
sys.getsizeof(a)

89095160

In [159]:
#np,array
b=np.arange(10000000,dtype=np.int8)
sys.getsizeof(b)

10000112

fancy indexing


In [160]:
#in fancy indexing we can fetch item we cant fetch by regular indexing(where we canot catch pattern)

In [178]:

a=np.arange(12).reshape(4,3)

In [179]:
a

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [180]:
#now we want to fetch row 1,2,3 which is unable to do by reagular indexing because we cant catch any pattern into it 

In [181]:
#to do that we use fancy indexing where we give element in form  of list


In [183]:
a[[1,2,3]]

array([[ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [184]:
#boolean indexing


In [190]:
a=np.random.randint(1,100,24).reshape(6,4)

In [191]:
a

array([[68, 65, 10, 55],
       [54, 83, 52, 46],
       [96, 17, 92, 28],
       [ 6, 23, 22, 31],
       [47, 97, 50, 69],
       [21, 57,  1, 28]], dtype=int32)

In [192]:
#find all number greater than 50


In [193]:
a>50

array([[ True,  True, False,  True],
       [ True,  True,  True, False],
       [ True, False,  True, False],
       [False, False, False, False],
       [False,  True, False,  True],
       [False,  True, False, False]])

In [196]:
a[a>50]

array([68, 65, 55, 54, 83, 52, 96, 92, 97, 69, 57], dtype=int32)

In [197]:
#even numbers


In [198]:
a%2==0

array([[ True, False,  True, False],
       [ True, False,  True,  True],
       [ True, False,  True,  True],
       [ True, False,  True, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [199]:
a[a%2==0]

array([68, 10, 54, 52, 46, 96, 92, 28,  6, 22, 50, 28], dtype=int32)

In [202]:
#number greater than 50 and even
a[(a>50)&(a%2==0)]

array([68, 54, 52, 96, 92], dtype=int32)