In [1]:
#np.sort-return a sorted copy of array

In [3]:
import numpy as np
a=np.random.randint(1,100,15)
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [5]:
b=np.random.randint(1,100,24).reshape(6,4)
b

array([[16, 33, 89, 97],
       [68, 99,  4, 17],
       [72, 67, 82, 23],
       [ 3, 96, 16, 60],
       [72, 86, 99, 49],
       [54, 81, 81, 62]], dtype=int32)

In [6]:
np.sort(a)

array([ 4, 24, 40, 43, 46, 50, 57, 61, 66, 66, 69, 73, 79, 85, 86],
      dtype=int32)

In [8]:
np.sort(b)#sorted array rowise

array([[16, 33, 89, 97],
       [ 4, 17, 68, 99],
       [23, 67, 72, 82],
       [ 3, 16, 60, 96],
       [49, 72, 86, 99],
       [54, 62, 81, 81]], dtype=int32)

In [9]:
np.sort(b,axis=0)#sorted array rowise

array([[ 3, 33,  4, 17],
       [16, 67, 16, 23],
       [54, 81, 81, 49],
       [68, 86, 82, 60],
       [72, 96, 89, 62],
       [72, 99, 99, 97]], dtype=int32)

In [10]:
np.sort(b,axis=1)

array([[16, 33, 89, 97],
       [ 4, 17, 68, 99],
       [23, 67, 72, 82],
       [ 3, 16, 60, 96],
       [49, 72, 86, 99],
       [54, 62, 81, 81]], dtype=int32)

In [11]:
np.sort(a)[::-1]

array([86, 85, 79, 73, 69, 66, 66, 61, 57, 50, 46, 43, 40, 24,  4],
      dtype=int32)

np.append


In [12]:
#add element in the end of array

In [13]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [14]:
np.append(a,200)

array([ 61,  85,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,
        50,   4, 200])

In [15]:
b

array([[16, 33, 89, 97],
       [68, 99,  4, 17],
       [72, 67, 82, 23],
       [ 3, 96, 16, 60],
       [72, 86, 99, 49],
       [54, 81, 81, 62]], dtype=int32)

In [20]:
np.append(b,np.ones((b.shape[0],1)),axis=1)

array([[16., 33., 89., 97.,  1.],
       [68., 99.,  4., 17.,  1.],
       [72., 67., 82., 23.,  1.],
       [ 3., 96., 16., 60.,  1.],
       [72., 86., 99., 49.,  1.],
       [54., 81., 81., 62.,  1.]])

np.concatenate

In [21]:
#(work as replacement of stack function)
#concatenate the sequence of array

In [23]:
c=np.arange(6).reshape(2,3)
d=np.arange(6,12).reshape(2,3)
print(c)
print(d)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [29]:
np.concatenate((c,d),axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

np.unique

In [30]:
#return uniqe values from array

In [32]:
e=np.array([1,1,1,2,2,3,3,4,4,5,6,7,7,8,8,9,9,10])
f=np.array([[1,2,3,1],[1,2,3,2]])

In [33]:
e

array([ 1,  1,  1,  2,  2,  3,  3,  4,  4,  5,  6,  7,  7,  8,  8,  9,  9,
       10])

In [34]:
f

array([[1, 2, 3, 1],
       [1, 2, 3, 2]])

In [36]:
np.unique(e)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [37]:
np.unique(f)

array([1, 2, 3])

np.expand_dims

In [42]:
a

(15,)

In [41]:
np.expand_dims((a),axis=0).shape

(1, 15)

np.where

In [43]:
#return the indexes of element where condition gets satisfied

In [44]:
a


array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [45]:
np.where(a>50)

(array([ 0,  1,  2,  5,  6,  7,  8,  9, 10]),)

In [46]:
#reeplace value >50 with 0

In [48]:
#np.whare(condition,true,false)

In [49]:
np.where(a>50,0,a)

array([ 0,  0,  0, 46, 40,  0,  0,  0,  0,  0,  0, 43, 24, 50,  4],
      dtype=int32)

np.argmax-return index of maximum number in an array

In [50]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [51]:
np.argmax(a)

np.int64(2)

In [52]:
b


array([[16, 33, 89, 97],
       [68, 99,  4, 17],
       [72, 67, 82, 23],
       [ 3, 96, 16, 60],
       [72, 86, 99, 49],
       [54, 81, 81, 62]], dtype=int32)

In [53]:
np.argmax(b,axis=0)

array([2, 1, 4, 0])

In [54]:
np.argmin(a)

np.int64(14)

In [55]:
np.argmin(b,axis=1)

array([0, 2, 3, 0, 3, 0])

In [56]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [57]:
np.cumsum(a)

array([ 61, 146, 232, 278, 318, 384, 453, 532, 605, 662, 728, 771, 795,
       845, 849])

In [58]:
b

array([[16, 33, 89, 97],
       [68, 99,  4, 17],
       [72, 67, 82, 23],
       [ 3, 96, 16, 60],
       [72, 86, 99, 49],
       [54, 81, 81, 62]], dtype=int32)

In [60]:
np.cumsum(b,axis=0)

array([[ 16,  33,  89,  97],
       [ 84, 132,  93, 114],
       [156, 199, 175, 137],
       [159, 295, 191, 197],
       [231, 381, 290, 246],
       [285, 462, 371, 308]])

In [61]:
np.cumprod(a)

array([                  61,                 5185,               445910,
                   20511860,            820474400,          54151310400,
              3736440417600,      295178792990400,    21548051888299200,
        1228238957633054400,  7276794908943383936,  -692468168496868224,
        1827508029784714240,  -858318879312046080, -3433275517248184320])

In [62]:
np.percentile

<function percentile at 0x0000022FC7AC2EF0>

In [63]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [65]:
np.percentile(a,50)

np.float64(61.0)

In [66]:
np.median(a)

np.float64(61.0)

np.histogram

np.histogram(a,bins=[0,50,100])

In [68]:
a.ndim

1

In [71]:
np.shape(a)

(15,)

corrcoef-correlation coefficient

In [74]:
salary=np.array([20000,40000,25000,35000,60000])
experiance=np.array([1,2,3,4,2])

In [75]:
np.corrcoef(salary,experiance)

array([[1.        , 0.04224095],
       [0.04224095, 1.        ]])

isin function

In [76]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [77]:
item=[10,20,30,40,50,60,70,75,80,90,100]


In [78]:
np.isin(a,item)

array([False, False, False, False,  True, False, False, False, False,
       False, False, False, False,  True, False])

In [80]:
a[np.isin(a,item)]

array([40, 50], dtype=int32)

np.flip-flip element first  to last and last to first

In [81]:
a

array([61, 85, 86, 46, 40, 66, 69, 79, 73, 57, 66, 43, 24, 50,  4],
      dtype=int32)

In [82]:
np.flip(a)

array([ 4, 50, 24, 43, 66, 57, 73, 79, 69, 66, 40, 46, 86, 85, 61],
      dtype=int32)

np.put-use to change element in the list

In [84]:
np.put(a,[0,1],[100,200])

In [85]:
a

array([100, 200,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,
        50,   4], dtype=int32)

np.delete-use to elements value wise

In [86]:
a

array([100, 200,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,
        50,   4], dtype=int32)

In [88]:
np.delete(a,0)

array([200,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,  50,
         4], dtype=int32)

set function

In [89]:
m=np.array([1,2,3,4,5])
n=np.array([3,4,5,6,7])

In [90]:
np.union1d(m,n)

array([1, 2, 3, 4, 5, 6, 7])

In [91]:
np.intersect1d(m,n)

array([3, 4, 5])

In [93]:
np.setdiff1d(m,n)

array([1, 2])

In [95]:
np.setxor1d(m,n)

array([1, 2, 6, 7])

In [96]:
np.in1d(a,4)

C:\Users\visha\AppData\Local\Temp\ipykernel_37276\2583897918.py:1: DeprecationWarning: `in1d` is deprecated. Use `np.isin` instead.
  np.in1d(a,4)


array([False, False, False, False, False, False, False, False, False,
       False, False, False, False, False,  True])

In [97]:
np.clip(a,a_min=25,a_max=75)

array([75, 75, 75, 46, 40, 66, 69, 75, 73, 57, 66, 43, 25, 50, 25],
      dtype=int32)

In [101]:
b

array([[16, 33, 89, 97],
       [68, 99,  4, 17],
       [72, 67, 82, 23],
       [ 3, 96, 16, 60],
       [72, 86, 99, 49],
       [54, 81, 81, 62]], dtype=int32)

In [100]:
np.swapaxes(b,0,1)

array([[16, 68, 72,  3, 72, 54],
       [33, 99, 67, 96, 86, 81],
       [89,  4, 82, 16, 99, 81],
       [97, 17, 23, 60, 49, 62]], dtype=int32)

In [116]:
#np.random.uniform(lowerboundvalue,higherboundvalue)
import random
np.random.uniform(0.0,100.0)

80.27859933695746

In [124]:
np.put(a,[0],[0])
a

array([  0, 200,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,
        50,   4], dtype=int32)

In [ ]:
#np.count_nonzero(a)-returns the count of value in arr

In [125]:
np.count_nonzero(a)

np.int64(14)

In [126]:
np.tile(a,4)#use to repeat the array reps time

array([  0, 200,  86,  46,  40,  66,  69,  79,  73,  57,  66,  43,  24,
        50,   4,   0, 200,  86,  46,  40,  66,  69,  79,  73,  57,  66,
        43,  24,  50,   4,   0, 200,  86,  46,  40,  66,  69,  79,  73,
        57,  66,  43,  24,  50,   4,   0, 200,  86,  46,  40,  66,  69,
        79,  73,  57,  66,  43,  24,  50,   4], dtype=int32)

In [128]:
np.repeat(a,4)#use to reapet indivisual value reps time

array([  0,   0,   0,   0, 200, 200, 200, 200,  86,  86,  86,  86,  46,
        46,  46,  46,  40,  40,  40,  40,  66,  66,  66,  66,  69,  69,
        69,  69,  79,  79,  79,  79,  73,  73,  73,  73,  57,  57,  57,
        57,  66,  66,  66,  66,  43,  43,  43,  43,  24,  24,  24,  24,
        50,  50,  50,  50,   4,   4,   4,   4], dtype=int32)